# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: de11e7b
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-latest
active: true
github_repo_name: boilercv
project_description: Computer vision routines suitable for nucleate pool boiling bubble
    analysis.
project_email: blake.naccarato@gmail.com
project_name: boilercv
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato, Kwang Jin Kim
project_version: 0.0.1
python_version: '3.11'
year_of_project_creation: 2022
