# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 9860b10
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-latest
advanced: false
docs_engine: MyST
github_repo_name: boilercv
include_funding: true
project_email: blake.naccarato+boilercv@gmail.com
project_name: boilercv
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
python_version: '3.11'
use_dvc: true
year_of_project_creation: 2022
